"""The rig: which directions get extracted, at what field of view.

This is the heart of the tool. A rig is a plain JSON file so it can be diffed,
version-controlled, shared, and generated by scripts.
"""

from __future__ import annotations

import json
import math
import os
from dataclasses import asdict, dataclass, field, replace
from pathlib import Path
from typing import Any, Iterator

SCHEMA_VERSION = 1

#: v360 clamps every rotation to this range and hard-errors outside it.
ROTATION_LIMIT = 180.0
#: v360 accepts fields of view in (0, 360].
FOV_LIMIT = 360.0

INTERPOLATIONS = {"near", "line", "linear", "cube", "cubic", "lanc", "lanczos",
                  "sp16", "spline16", "gauss", "gaussian", "mitchell"}
FORMATS = {"jpg", "png"}


class RigError(ValueError):
    """A rig is malformed or physically impossible."""


def wrap180(degrees: float) -> float:
    """Fold an angle into v360's [-180, 180].

    Rigs are naturally written with yaws like 0/120/240 -- ring layouts come out of a
    loop that way. v360 rejects 240 outright, so every angle passes through here on
    its way to the filter graph.
    """
    wrapped = math.remainder(float(degrees), 360.0)
    # remainder() can return exactly -180.0; both ends are legal, keep the positive one.
    return 180.0 if wrapped == -180.0 else wrapped


@dataclass
class Camera:
    """One virtual pinhole camera pointed into the sphere."""

    name: str
    yaw: float = 0.0
    pitch: float = 0.0
    roll: float = 0.0
    h_fov: float = 90.0
    v_fov: float = 70.0
    enabled: bool = True

    def validate(self, where: str = "camera") -> None:
        if not self.name or not self.name.strip():
            raise RigError(f"{where}: name must not be empty")
        if any(ch in self.name for ch in r'\/:*?"<>|'):
            raise RigError(f"{where} {self.name!r}: name contains characters illegal in a filename")
        for axis in ("yaw", "pitch", "roll"):
            value = getattr(self, axis)
            if not math.isfinite(value):
                raise RigError(f"{where} {self.name!r}: {axis} must be a finite number")
        for axis in ("h_fov", "v_fov"):
            value = getattr(self, axis)
            if not math.isfinite(value) or not 0.0 < value <= FOV_LIMIT:
                raise RigError(
                    f"{where} {self.name!r}: {axis} must be in (0, {FOV_LIMIT:g}], got {value}"
                )

    def normalized(self) -> "Camera":
        """A copy with rotations folded into the range v360 will accept."""
        return replace(self, yaw=wrap180(self.yaw), pitch=wrap180(self.pitch),
                       roll=wrap180(self.roll))


def native_size(source_width: int, h_fov: float, v_fov: float) -> tuple[int, int]:
    """Output size that preserves the source's own pixel density.

    An equirectangular frame carries `source_width` pixels across 360 degrees, and
    because it is 2:1 the vertical density is identical. So a camera covering
    `h_fov` degrees deserves exactly `source_width * h_fov / 360` pixels across.

    Smaller than this throws away detail the capture paid for; larger invents it and
    inflates the dataset without adding a single real feature for photogrammetry to
    match. Sizes are rounded to even numbers because several encoders insist on it.
    """
    per_degree = source_width / 360.0
    width = max(int(round(h_fov * per_degree / 2)) * 2, 2)
    height = max(int(round(v_fov * per_degree / 2)) * 2, 2)
    return width, height


def output_size(output: "Output", camera: "Camera", source_width: int) -> tuple[int, int]:
    """The size one camera is actually written at.

    The single source of truth for this. Extraction and the COLMAP export both need it,
    and when they computed it separately they drifted: the export always assumed
    automatic sizing, so a rig with a fixed size exported intrinsics that did not match
    its own images. COLMAP accepts those happily and reconstructs something wrong.
    """
    if output.auto and source_width:
        return native_size(source_width, camera.h_fov, camera.v_fov)
    return output.width, output.height


@dataclass
class Output:
    """Image dimensions and encoding for extracted frames."""

    width: int = 1920
    height: int = 1440
    format: str = "jpg"
    quality: int = 2  # ffmpeg -q:v, 2 is visually lossless-ish; ignored for png
    interp: str = "line"
    #: Derive each camera's size from the source resolution and its own field of
    #: view, ignoring width/height. This is the sensible default: it keeps native
    #: detail without upscaling, and it is per-camera, so a narrow camera in a mixed
    #: rig is not forced to the same pixel count as a wide one.
    auto: bool = True

    def validate(self) -> None:
        for axis in ("width", "height"):
            value = getattr(self, axis)
            if not isinstance(value, int) or not 0 < value <= 32767:
                raise RigError(f"output.{axis} must be an integer in (0, 32767], got {value}")
        if self.format not in FORMATS:
            raise RigError(f"output.format must be one of {sorted(FORMATS)}, got {self.format!r}")
        if self.format == "jpg" and not 1 <= self.quality <= 31:
            raise RigError(f"output.quality must be in [1, 31] (lower is better), got {self.quality}")
        if self.interp not in INTERPOLATIONS:
            raise RigError(
                f"output.interp must be one of {sorted(INTERPOLATIONS)}, got {self.interp!r}"
            )

    @property
    def aspect(self) -> float:
        return self.width / self.height


@dataclass
class Orientation:
    """Rig-level rotation, applied on top of every camera.

    This is how you level a tilted capture (camera mounted at an angle on a car roof)
    without editing every camera in the rig.
    """

    yaw: float = 0.0
    pitch: float = 0.0
    roll: float = 0.0

    def validate(self) -> None:
        for axis in ("yaw", "pitch", "roll"):
            if not math.isfinite(getattr(self, axis)):
                raise RigError(f"orientation.{axis} must be a finite number")


@dataclass
class Rig:
    """A named set of cameras plus how to render them."""

    name: str = "rig"
    cameras: list[Camera] = field(default_factory=list)
    output: Output = field(default_factory=Output)
    orientation: Orientation = field(default_factory=Orientation)
    #: Occluder definitions, consumed by the masking milestone. Carried through
    #: untouched for now so rigs written today stay valid.
    occluders: list[dict[str, Any]] = field(default_factory=list)

    # -- validation ---------------------------------------------------------

    def validate(self) -> None:
        if not self.cameras:
            raise RigError("rig has no cameras")
        self.output.validate()
        self.orientation.validate()

        seen: set[str] = set()
        for index, camera in enumerate(self.cameras):
            camera.validate(f"cameras[{index}]")
            key = camera.name.casefold()
            if key in seen:
                raise RigError(f"duplicate camera name {camera.name!r} -- names become filenames")
            seen.add(key)

        if not self.enabled_cameras:
            raise RigError("every camera in the rig is disabled")

    def warnings(self) -> list[str]:
        """Non-fatal problems worth telling the user about before a long render."""
        notes: list[str] = []
        target = self.output.aspect
        for camera in self.cameras:
            if not camera.enabled:
                continue
            # v360 maps h_fov/v_fov onto w/h independently, so mismatched ratios
            # silently stretch the image rather than erroring. Automatic sizing
            # derives the size from the fov, so it cannot mismatch.
            fov_ratio = camera.h_fov / camera.v_fov
            if not self.output.auto and abs(fov_ratio - target) > 0.02 * target:
                notes.append(
                    f"camera {camera.name!r}: fov ratio {fov_ratio:.3f} does not match output "
                    f"aspect {target:.3f} -- the image will be anisotropically stretched"
                )
            if camera.h_fov >= 180.0:
                notes.append(
                    f"camera {camera.name!r}: h_fov {camera.h_fov:g} is extreme for a rectilinear "
                    "projection; edges will be heavily distorted and near-useless for feature matching"
                )
        return notes

    # -- accessors ----------------------------------------------------------

    @property
    def enabled_cameras(self) -> list[Camera]:
        return [c for c in self.cameras if c.enabled]

    def normalized_cameras(self) -> list[Camera]:
        """Enabled cameras with rig orientation folded in and angles wrapped.

        Rig orientation is added to each camera before wrapping, which is why a rig
        levelled by -7 degrees of pitch does not have to touch its cameras.
        """
        result = []
        for camera in self.enabled_cameras:
            combined = replace(
                camera,
                yaw=camera.yaw + self.orientation.yaw,
                pitch=camera.pitch + self.orientation.pitch,
                roll=camera.roll + self.orientation.roll,
            )
            result.append(combined.normalized())
        return result

    def __iter__(self) -> Iterator[Camera]:
        return iter(self.cameras)

    def __len__(self) -> int:
        return len(self.cameras)

    # -- serialization ------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": SCHEMA_VERSION,
            "name": self.name,
            "orientation": asdict(self.orientation),
            "output": asdict(self.output),
            "cameras": [asdict(c) for c in self.cameras],
            "occluders": self.occluders,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent) + "\n"

    def save(self, path: str | os.PathLike[str]) -> Path:
        # An empty string becomes Path('.'), and writing to a directory fails deep
        # inside pathlib with a bare "Permission denied: '.'" that says nothing about
        # what the caller actually did wrong.
        text = str(path).strip()
        if not text:
            raise RigError("no filename given: enter a path like rigs/my-rig.json")

        target = Path(text)
        if target.is_dir():
            raise RigError(f"{target} is a directory -- give a filename, e.g. {target / 'rig.json'}")
        if not target.suffix:
            target = target.with_suffix(".json")

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(self.to_json(), encoding="utf-8")
        return target

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Rig":
        version = data.get("version", SCHEMA_VERSION)
        if version > SCHEMA_VERSION:
            raise RigError(
                f"rig uses schema version {version}, this build understands "
                f"up to {SCHEMA_VERSION} -- upgrade 360extract"
            )

        try:
            cameras = [Camera(**c) for c in data.get("cameras", [])]
            output = Output(**data.get("output", {}))
            orientation = Orientation(**data.get("orientation", {}))
        except TypeError as exc:
            raise RigError(f"unrecognized field in rig: {exc}") from exc

        rig = cls(
            name=data.get("name", "rig"),
            cameras=cameras,
            output=output,
            orientation=orientation,
            occluders=data.get("occluders", []),
        )
        rig.validate()
        return rig

    @classmethod
    def load(cls, path: str | os.PathLike[str]) -> "Rig":
        source = Path(path)
        if not source.exists():
            raise RigError(f"no such rig file: {source}")
        try:
            # utf-8-sig so a rig hand-edited in Notepad or written by PowerShell's
            # Set-Content still opens; both prepend a byte order mark.
            data = json.loads(source.read_text(encoding="utf-8-sig"))
        except json.JSONDecodeError as exc:
            raise RigError(f"{source} is not valid JSON: {exc}") from exc
        if not isinstance(data, dict):
            raise RigError(f"{source} must contain a JSON object")
        return cls.from_dict(data)


# -- presets ----------------------------------------------------------------
#
# Every preset returns a validated rig. They exist so that the common cases never
# require hand-writing JSON.


def _fov_for(output: Output, h_fov: float) -> float:
    """Vertical fov that keeps pixels square at the given output aspect."""
    return h_fov / output.aspect


def ring(count: int = 8, pitch: float = 0.0, h_fov: float = 90.0,
         output: Output | None = None, name: str | None = None) -> Rig:
    """`count` cameras evenly spaced around the horizon.

    The photogrammetry workhorse. Adjacent cameras overlap when count * h_fov > 360,
    which feature matching needs -- 8 cameras at 90 degrees gives 2x coverage.
    """
    if count < 1:
        raise RigError(f"ring needs at least 1 camera, got {count}")
    output = output or Output()
    step = 360.0 / count
    cameras = [
        Camera(
            name=f"c{index:02d}",
            yaw=wrap180(index * step),
            pitch=pitch,
            h_fov=h_fov,
            v_fov=_fov_for(output, h_fov),
        )
        for index in range(count)
    ]
    rig = Rig(name=name or f"ring-{count}", cameras=cameras, output=output)
    rig.validate()
    return rig


def cube(output: Output | None = None) -> Rig:
    """Six 90-degree faces. Complete spherical coverage with no overlap."""
    output = output or Output(width=1024, height=1024)
    directions = [
        ("front", 0.0, 0.0), ("right", 90.0, 0.0), ("back", 180.0, 0.0),
        ("left", -90.0, 0.0), ("up", 0.0, 90.0), ("down", 0.0, -90.0),
    ]
    cameras = [
        Camera(name=n, yaw=wrap180(y), pitch=p, h_fov=90.0, v_fov=90.0)
        for n, y, p in directions
    ]
    rig = Rig(name="cube6", cameras=cameras, output=output)
    rig.validate()
    return rig


def dome(ring_count: int = 8, upper_pitch: float = 30.0, h_fov: float = 90.0,
         output: Output | None = None) -> Rig:
    """Horizon ring plus an upward ring plus zenith. Everything except the ground.

    The default answer for handheld capture: the operator and the stick live below
    the horizon, and this rig simply never looks there.
    """
    output = output or Output()
    v_fov = _fov_for(output, h_fov)
    cameras: list[Camera] = []
    step = 360.0 / ring_count
    for index in range(ring_count):
        cameras.append(Camera(name=f"h{index:02d}", yaw=wrap180(index * step),
                              pitch=0.0, h_fov=h_fov, v_fov=v_fov))
    for index in range(ring_count):
        cameras.append(Camera(name=f"u{index:02d}", yaw=wrap180(index * step + step / 2),
                              pitch=upper_pitch, h_fov=h_fov, v_fov=v_fov))
    cameras.append(Camera(name="zenith", yaw=0.0, pitch=90.0, h_fov=h_fov, v_fov=v_fov))
    rig = Rig(name=f"dome-{ring_count}", cameras=cameras, output=output)
    rig.validate()
    return rig


def car_forward(h_fov: float = 90.0, pitch: float = -5.0,
                output: Output | None = None) -> Rig:
    """Roof-mounted capture on a moving vehicle.

    Five cameras covering forward and both sides, tilted slightly down to catch road
    surface and building bases. Deliberately no rear camera: on a car mount the rear
    is usually the operator, the mount arm, or the vehicle's own roof box. Add one
    back if your mount is clean.

    Carries a nadir occluder covering the roof, which the masking milestone consumes.
    """
    output = output or Output()
    v_fov = _fov_for(output, h_fov)
    directions = [("fwd", 0.0), ("fwd_left", -45.0), ("fwd_right", 45.0),
                  ("left", -90.0), ("right", 90.0)]
    cameras = [
        Camera(name=n, yaw=y, pitch=pitch, h_fov=h_fov, v_fov=v_fov)
        for n, y in directions
    ]
    rig = Rig(name="car-forward", cameras=cameras, output=output,
              occluders=[{"type": "nadir_cone", "angle": 40}])
    rig.validate()
    return rig


def handheld(ring_count: int = 6, pitch: float = 10.0, h_fov: float = 90.0,
             output: Output | None = None) -> Rig:
    """Walking capture on a selfie stick.

    Tilted slightly up so the operator, their shadow and the stick stay out of frame,
    with a nadir occluder for whatever still creeps in at the bottom edge.
    """
    output = output or Output()
    rig = ring(ring_count, pitch=pitch, h_fov=h_fov, output=output, name="handheld")
    rig.occluders = [{"type": "nadir_cone", "angle": 45}]
    rig.validate()
    return rig


PRESETS = {
    "ring": ring,
    "cube": cube,
    "dome": dome,
    "car-forward": car_forward,
    "handheld": handheld,
}
